### ISSUE TITLE
Legend problem with classification plot, Matlab auto-update legend issue

### ISSUE THREAD

**Issue by coldformed** [thinwalled/cufsm-git#2]
Legend problems with classification plot in post-processor. Matlab changed to auto legend update and extra entries are cropping up in the classification plot and other places. Need to go through all instances of legend and turn off the auto updating. Thanks mathworks.

**Comment by SJin24** [comment]
I tried this method, looks like it works:
In function "thecurve3.m", after the sentence:
hndl2(cr)=plot(curve_sign(m+1,1),curve_sign(m+1,2),'o');
add one line: hndl2(cr).Annotation.LegendInformation.IconDisplayStyle='off';
It will be excluded from the legend.

**Comment by coldformed** [comment]
I was going to try this...
legend('legend_text','AutoUpdate','off')
I think that is also supposed to work and is a little less obscure, if you are willing to try that let me know. If you fix it just push the commit to me, happy to review and accept! Saves me time fixing it myself. 

Might be an issue in other plots too...

**Comment by SJin24** [comment]
OK, I'll fix it.
