### ISSUE TITLE
Displays of deformations subjected to simple-clamped (S-C) boundary condition

### ISSUE THREAD

**Issue by SJin24** [thinwalled/cufsm-git#20]
According to literatures, the shape function used in CUFSM for S-C boundary condition is: Y[m]=sin[(m+1) * pi * y/a]+[(m+1)/m] * sin(m * pi * y/a).
The last “m” in this function was missed in some CUFSM files, where the function was input as Y[m]=……+……* sin(pi * y/a).
The error can be such reproduced:
- the default example of CUFSM (a lipped channel beam, 10 nodes).
- select “General boundary condition solution” type, and “simple-clamped (S-C)” boundary condition, then perform “Elastic Buckling” analysis. This will lead to solutions to two member lengths (92 and 192) with 20 longitudinal terms (1~20).
- in the “Analysis Post-Processor” page, the 3D deformation is correct, the buckling mode No. 1 at the length of 92 is dominated by two-half-wave longitudinal function. However, the 2D in-plane mode is not correctly plotted. Changing the “Cross section position y/L (2D)” value in the range 0.1~0.9 will show that.

**Comment by SJin24** [comment]
Trying to fix it through pull request #21

**Comment by coldformed** [comment]
For the default section and load with S-C, at 92 in., mode 2 or mode 3 have some high m content m=18, m=19 - that is perhaps just there to cancel things out to get the S-C shape - but surprising not to see more waves in the 3D model. 

That said, appreciate your persistence with finding this bug.
