### ISSUE TITLE
Need 4 Speed? How about a new turbo for UI displaying?

### ISSUE THREAD

**Issue by SJin24** [thinwalled/cufsm-git#25]
Sandor and Damir have complained more than once to me about the slow UI displaying. It’s mainly the “Post-Processor” page where there are many UI controls.
I have discussed this problem with Professor Schafer. We are clear about the reason: UIs here are generated by .m files but not .fig files. If by .fig files, the displaying will be faster, but the codes will become lengthy due to the corresponding OOP kind of things. It’s not difficult but we don’t like it. We want to keep the codes neat and tidy.
I was considering this problem for several months, and figured out a way to partially solve this problem these days, all based on .m files. It is as such:
The first time when we generate the “Post-Processor” page, the speed will be the same as before, it is still the .m file that produce the UIs. But after that the UIs will be safely stored and not get cleared when switching to other pages,. As the result, whenever we switch back to this page, there will be no need to regenerate it. Things become faster.
I’ve tested this method and it works.
There is only one more thing that could take us a little bit time for coding: we need a new “update” action to the UIs when switching back to this page. Currently when we switch back, every UIs are regenerated and initialized. It should be better if the previous settings of the UIs can be kept (the proposed method can), but of course some necessary updates are needed.
So, what do you think about it? Does it worth a try?

**Comment by coldformed** [comment]
I'm interested. But wary if it confuses things. Maybe do it for just one page and show me, then I can see more deeply.

The post-processor is uniquely slow. Somehow it is more than just all the elements I think.

I have been wondering if part of it is order and how I do things. If the axes for the plots are not updated until after the GUI elements are written, would that be faster. Also, I jump around with the GUI elements is that slowing things down. Even the PMM page on the loads pre-processor is much faster than the post-processor page. I still think, I have made some additional mistake or strange thing beyond just having a lot of elements.

**Comment by SJin24** [comment]
About this issue, I have good news and bad news. 
Good news is that this problem has been perfectly solved. Even the first time generating the “Post-Processor” page is quick.
Bad news is for me: the solution has nothing to do with my previous proposal. 
I changed the generating order, GUIs first and then plots, as suggested Prof. Schafer, then problem solved. 
So, next, I will do it in the comparout.m and compareout_cb.m with minimum modifications to the original codes.  
Then, maybe someday we can introduce a mechanism for maintaining the user data of the GUIs, so that it can act more like normal dialog boxes.

**Comment by coldformed** [comment]
OK, let's take the win! 

Let's finish the vectorization merge, then start this as the next pull request issue.

**Comment by coldformed** [comment]
Closing this issue, based on latest merged commits.
