### ISSUE TITLE
Color on out-of-plane 2D buckling mode (warping) shapes

### ISSUE THREAD

**Issue by coldformed** [thinwalled/cufsm-git#32]
When you change scale from +1 to -1 and plot the warping (or out-of-plane) shape the direction of the warping displacements change but the color stays the same. So red switches from inward to outward. Seems weird, would expect color to be related to a direction so that color should change. 

Noticed this because I was exploring the impact of inward vs. outward flange distortional buckling on the end warping of the free lip of a lipped channel or sigma. Just need to correct the color then this big should be settled. The direction is as expected.

**Comment by SJin24** [comment]
Professor, I have pulled an request to solve this problem. Please take a look to see if it is right.
