### ISSUE TITLE
Cross-section generator after a successful analysis can crash CUFSM

### ISSUE THREAD

**Issue by coldformed** [thinwalled/cufsm-git#35]
If you open generator accidentally, but then do not want to change anything, the model crashes, no way to easily undo opening generator and keeping current model. This happens specifically after a successful analysis has been performed.

Bug reported by Kara Peterman and her students. Need to recreate, then fork and fix.

**Comment by SJin24** [comment]
The following process can cause a crash of the program. I don't if it is the same bug reported by Prof. Peterman.
1 Run “cufsm5.m”.
2 Select menu item “1.Input | C/Z Template”.
3 Close the “C and Z Template” dialog box.
4 Select the menu item “1.Input | C/Z Template” again.
Then the program crushes.

In the files for “Preprocessor screen”, such as the file “pre2.m”, there is a global variable named “flags”, which is assumed to be a 10-element vector indicating showing [node# element# mat# stress# stresspic coord constraints springs origin propaxis] or not in the plot.
A call to the “C/Z Template” will cause a call to the file “template.m”. In this file, the global variable “flags” will be redefined as a 9-element vector.
This 9-element vector “flags” can cause an error during the display of “Preprocessor screen”.

I recommend that we don’t claim the variable “flags” as a global variable in the file “template.m”. This method has been tested to be effective.

**Comment by SJin24** [comment]
And yes, I also found a call to the “C/Z Template” will soon change the current model, even we haven’t submitted the data to input. This is also because of the reevaluating to the global variables “prop, node, elem, lengths, springs”, and “constraints”. Using different variables in the file “template.m” and “template_cb.m” can solve this problem, and I think it should be even better if we limit the global declaration of these parameters.

**Comment by coldformed** [comment]
My/CUFSM's handling of global variables is a proper mess. I agree with your fixes. A comprehensive review of global variables and limiting it down to only those necessary is certainly needed - but not something I have an appetite for in the near term.

**Comment by coldformed** [comment]
@SJin24 did you put a commit up on this one? I thought I saw one, but might have been mistaken.

**Comment by SJin24** [comment]
Yes. I prepared the update in my fork for this one and planned to pull a new request after the merge of the previous commit, but after I pressed a button, something like synchronizing, it was submitted automatically.

**Comment by coldformed** [comment]
OK, so we think the template issue is fixed in the main branch?

From: SJin24 ***@***.***>
Date: Friday, May 10, 2024 at 9:48 AM
To: thinwalled/cufsm-git ***@***.***>
Cc: Ben Schafer ***@***.***>, Author ***@***.***>
Subject: Re: [thinwalled/cufsm-git] Cross-section generator after a successful analysis can crash CUFSM (Issue #35)

Yes. I prepared the update in my fork for this one and planned to pull a new request after the merge of the previous commit, but after I pressed a button, something like synchronizing, it was submitted automatically.

**Comment by SJin24** [comment]
Yes. I think this problem has been fixed according to the current codes in the main branch.

**Comment by coldformed** [comment]
Great. I’ll check and close out if it seems working.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
