### ISSUE TITLE
The previous cFSM modal classification solution not cleared can cause an error during the next modal classification

### ISSUE THREAD

**Issue by SJin24** [thinwalled/cufsm-git#7]
I suggest clear the cFSM modal classification solution (the cell variable “clas”) each time before performing a classification. It may sometimes cause an error if not cleared. The error can be reproduced as such:
-the default example of CUFSM (a lipped channel beam, 10 nodes)
-set the cFSM to be “on” with all G D L O base vectors selected
-perform elastic buckling analysis
-in the “Analysis Post-Processor”, conduct cFSM modal “Classify”
-go back to cFSM settings, and unselect the “Distortional” base vectors
-perform buckling analysis again
-in the “Analysis Post-Processor”, switch to “load factor vs mode numbers”, then “supplemental participation plot”
An error will be encountered, because now we have 19 buckling curves but 20 classification solutions. The last one is the solution of the previous identification but not got cleared.

**Comment by coldformed** [comment]
Good catch. Go ahead and implement I will merge the change.
