### ISSUE TITLE
Move log of changes out of cufsm5 into conventional logging file per @damir's suggestion

### ISSUE THREAD

**Issue by coldformed** [thinwalled/cufsm-git#9]
Move log of changes out of cufsm5 into conventional logging file per @damir's suggestion. Can we also have any auto logging so that description of merged commits handle things? What about version numbering does it increment with every new commit??

**Comment by AkchurinDA** [comment]
I don't think automatic logging is easily implementable. Generally, I don't think that automatic logging is even practiced - at least I have not seen any real cases. It is more of a convention to keep a very high-level log of all updates in `NEWS.md` files like I do in my [repo](https://github.com/AkchurinDA/Fortuna.jl/blob/main/NEWS.md). This is typically done to avoid having comments not related to code in main files (like in the case of `cufsm5.m`). If you want, I can create a quick pull request with cleaned up history from `cufsm5.m` file moved into `NEWS.md` file.

**Comment by AkchurinDA** [comment]
@coldformed,
Preliminary version of how it is going to look like is in pull request #19.

**Comment by coldformed** [comment]
You can get list of all committs when you make a release, and potentially add that as version 1 for news.md

**Comment by coldformed** [comment]
This change has been made and is now merged.
